version: '3.9'

services:

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/backend
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - REDIS_HOST=redis
    depends_on:
      - redis

  frontend:
    build:
      context: .
      dockerfile: docker/frontend/Dockerfile
    ports:
      - "5173:5173"  
    volumes:
      - ./frontend:/app
    environment:
      - NODE_ENV=development
#      - VITE_API_URL = "http://localhost:5000"
      - VITE_API_URL = "http://backend:5000"
